version: '3'

volumes:
  tenuki:
services:
  db:
    image: mariadb:latest
    env_file: .env
    volumes:
      - ./mariadb:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
  soycms:
    image: aldentea/php_soycms:3.2.1
    volumes: 
      - ./soycms/config:/var/www/soy/common/config
      - ./soycms/db:/var/www/soy/common/db
      - ./httpd/conf/sites-available:/etc/apache2/sites-available
      - ./httpd/log:/var/log/apache2
      - ./php/conf.d:/usr/local/etc/php/conf.d
      - ./sites/:/var/www/
      - tenuki:/var/www/soy/ # /var/www/soy はホスト側と同期しない。
    depends_on:
      - db
    env_file: .env
    ports: 
      - '8008:80'
    restart: always

